servingRuntime:
  name: vllm-serving-runtime
  knativeTimeout: 60m
  env:
  - name: HOME
    value: /vllm
  - name: HF_TOKEN
    valueFrom:
      secretKeyRef:
        key: HF_TOKEN
        name: huggingface-secret
  volumeMounts:
  - mountPath: /dev/shm
    name: shm
  - mountPath: /vllm
    name: vllm-home
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 2Gi
    name: shm
  - emptyDir:
      sizeLimit: 5Gi
    name: vllm-home

hf_token: ""