apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
 name: vllm-sidecar
 namespace: {{ .Release.Namespace }}
spec:
 mode: sidecar
 config:
   exporters:
     debug:
       verbosity: detailed
     otlphttp/dynatrace:
       endpoint: 'https://rpr13334.live.dynatrace.com/api/v2/otlp'
       headers:
         Authorization: Api-Token xx.XX
   processors:
     batch:
       send_batch_size: 100
       timeout: 1s
     cumulativetodelta: {}
     memory_limiter:
       check_interval: 5s
       limit_percentage: 95
       spike_limit_percentage: 25
   receivers:
     otlp:
       protocols:
         grpc:
           endpoint: '0.0.0.0:4317'
         http:
           endpoint: '0.0.0.0:4318'
     prometheus:
       config:
         scrape_configs:
           - job_name: vllm-llama-serve
             scrape_interval: 5s
             static_configs:
               - targets:
                   - 'localhost:8000'
   service:
     pipelines:
       metrics:
         exporters:
           - otlphttp/dynatrace
           - debug
         processors:
           - memory_limiter
           - cumulativetodelta
           - batch 
         receivers:
           - prometheus

